---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html/api
    - /bin/cp -R dist $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R prisma $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH